[build]
  command = "npx vite build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions.scheduler]
  cron = "*/1 * * * *"
  function = "scheduler"
